services:
  # FastAPI service
  fastapi:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres_db
    depends_on:
      - postgres

  # PostgreSQL service
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data


# Volumes to persist data
volumes:
  postgres-data:
